name: test-minimalist
on: [pull_request]

jobs:
  test:
    name: test-minimalist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.2
